spring:
  profiles:
    include: secret

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/opentheDoor
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  redis:
    refresh-token:
      host: localhost
      port: 6377
    fcm-token:
      host: localhost
      port: 6378
    bookmark:
      host: localhost
      port: 6379
    sorting:
      host: localhost
      port: 6376

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace
