spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 868bb44bb8f128728318399f8e7b888a
            redirect-uri: http://localhost:8080/members/login/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image
