server:
  servlet:
    context-path: /api

spring:
  profiles:
    include: oauth

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/opentheDoor
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace
