fcm:
  certification: fcm/openthedoor-930e4-firebase-adminsdk-t332b-aa9888ba26.json
server:
  port: 8081

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: rainbowgon
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer