fcm:
  certification: fcm/openthedoor-firebase-adminsdk.json
  certification2: fcm/fcm-token.json


server:
  port: 8081

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9093
      group-id: rainbowgon
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9093
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


  profiles:
    include: secret

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  redis:
    notification:
      host: localhost
      port: 6379

  logging:
    level:
      org.hibernate.sql: debug
      org.hibernate.type: trace