server:
  port: 80

eureka:
  instance:
    ip-address: 10.0.2.33
    instance-id:
      ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://10.0.2.13:80/eureka

spring:
  application:
    name: sender-server

  rabbitmq:
    host: 10.0.2.27
    port: 5672
    username: admin
    password: ssafyrainbowgon!!

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
      logging.level:
        org.hibernate.SQL: debug

  datasource:
    url: jdbc:mysql://ssafy-otd-rds.cd2yhtictcph.ap-northeast-2.rds.amazonaws.com:3306/otd-notification-db
    username: admin
    password: ssafyrainbowgon!!
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    notification:
      host: 10.0.4.196
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
  endpoint:
    health:
      show-details: always